In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv('With Yeo Johnson 80-20 Applying Hyperparameter BFE Top 4 features.csv')
df2 = pd.read_csv('With Yeo Johnson 80-20 Applying Hyperparameter BFE Top 5 features.csv')
df3 = pd.read_csv('With Yeo Johnson 80-20 Applying Hyperparameter BFE Top 7 features.csv')
df4 = pd.read_csv('With Yeo Johnson 80-20 Applying Hyperparameter BFE Top 9 features.csv')

In [3]:
df4

,Unnamed: 0,0,1,2,3,4,5
0,Metrics,Accuracy,Precision,Recall,F1 Score,Cohen Kappa,AUC
1,SVC,0.9101731601731602,0.9245283018867925,0.9245283018867925,0.9245283018867925,0.8767441860465116,0.987037037037037
2,LR,0.8577922077922077,0.8655806867455761,0.8679245283018868,0.863924235775925,0.7840512223515717,0.9735714285714286
3,KNN,0.8577922077922079,0.8932380171100434,0.8867924528301887,0.8886851104915043,0.817451205510907,0.9635569985569985

In [4]:
df2 = df2.drop(0, axis=0)
df3 = df3.drop(0, axis=0)
df4 = df4.drop(0, axis=0)
df2

,Unnamed: 0,0,1,2,3,4,5
1,SVC,0.9290043290043289,1.0,1.0,1.0,1.0,0.9953703703703703
2,LR,0.9004329004329005,0.9256220946130708,0.9245283018867925,0.920919486706486,0.8753674309229865,0.9842592592592593
3,KNN,0.9149350649350649,0.9153404429860541,0.9056603773584906,0.9082809224318658,0.8489167616875712,0.9858946608946608

In [5]:
df = pd.concat([df1, df2, df3, df4])
df

,Unnamed: 0,0,1,2,3,4,5
0,Metrics,Accuracy,Precision,Recall,F1 Score,Cohen Kappa,AUC
1,SVC,0.9428571428571428,0.963162623539982,0.9622641509433962,0.9623017177418597,0.9385507246376812,0.9962962962962963
2,LR,0.8861471861471862,0.9256220946130708,0.9245283018867925,0.920919486706486,0.8753674309229865,0.9796296296296297
3,KNN,0.9147186147186147,0.935062893081761,0.9245283018867925,0.9279016880095048,0.8787878787878788,0.9873809523809524
1,SVC,0.9290043290043289,1.0,1.0,1.0,1.0,0.9953703703703703
2,LR,0.9004329004329005,0.9256220946130708,0.9245283018867925,0.920919486706486,0.8753674309229865,0.9842592592592593
3,KNN,0.9149350649350649,0.9153404429860541,0.9056603773584906,0.9082809224318658,0.8489167616875712,0.9858946608946608
1,SVC,0.9294372294372295,1.0,1.0,1.0,1.0,1.0
2,LR,0.8625541125541124,0.8655806867455761,0.8679245283018868,0.863924235775925,0.7840512223515717,0.9702886002886003
3,KNN,0.8954545454545455,0.9353099730458221,0.8867924528301887,0.8979554187878527,0.8245033112582781,0.9768302068302068
1,SVC,0.9101731601731602,0.9245283018867925,0.9245283018867925,0.9245283018867925,0.8767441860465116,0.987037037037037
2,LR,0.8577922077922077,0.8655806867455761,0.8679245283018868,0.863924235775925,0.7840512223515717,0.9735714285714286
3,KNN,0.8577922077922079,0.8932380171100434,0.8867924528301887,0.8886851104915043,0.817451205510907,0.9635569985569985

In [6]:
df = df.drop(0, axis=0)

In [7]:
df.rename(columns={'Unnamed: 0': 'Model', '0': 'Accuracy', '1': 'Precision', '2': 'Recall', '3': 'F1 Score', '4': 'Cohen Kappa', '5': 'AUC'}, inplace=True)

In [8]:
df

,Model,Accuracy,Precision,Recall,F1 Score,Cohen Kappa,AUC
1,SVC,0.9428571428571428,0.963162623539982,0.9622641509433962,0.9623017177418597,0.9385507246376812,0.9962962962962963
2,LR,0.8861471861471862,0.9256220946130708,0.9245283018867925,0.920919486706486,0.8753674309229865,0.9796296296296297
3,KNN,0.9147186147186147,0.935062893081761,0.9245283018867925,0.9279016880095048,0.8787878787878788,0.9873809523809524
1,SVC,0.9290043290043289,1.0,1.0,1.0,1.0,0.9953703703703703
2,LR,0.9004329004329005,0.9256220946130708,0.9245283018867925,0.920919486706486,0.8753674309229865,0.9842592592592593
3,KNN,0.9149350649350649,0.9153404429860541,0.9056603773584906,0.9082809224318658,0.8489167616875712,0.9858946608946608
1,SVC,0.9294372294372295,1.0,1.0,1.0,1.0,1.0
2,LR,0.8625541125541124,0.8655806867455761,0.8679245283018868,0.863924235775925,0.7840512223515717,0.9702886002886003
3,KNN,0.8954545454545455,0.9353099730458221,0.8867924528301887,0.8979554187878527,0.8245033112582781,0.9768302068302068
1,SVC,0.9101731601731602,0.9245283018867925,0.9245283018867925,0.9245283018867925,0.8767441860465116,0.987037037037037
2,LR,0.8577922077922077,0.8655806867455761,0.8679245283018868,0.863924235775925,0.7840512223515717,0.9735714285714286
3,KNN,0.8577922077922079,0.8932380171100434,0.8867924528301887,0.8886851104915043,0.817451205510907,0.9635569985569985

In [9]:
df = df.sort_values('Model')

In [10]:
df

,Model,Accuracy,Precision,Recall,F1 Score,Cohen Kappa,AUC
3,KNN,0.9147186147186147,0.935062893081761,0.9245283018867925,0.9279016880095048,0.8787878787878788,0.9873809523809524
3,KNN,0.9149350649350649,0.9153404429860541,0.9056603773584906,0.9082809224318658,0.8489167616875712,0.9858946608946608
3,KNN,0.8954545454545455,0.9353099730458221,0.8867924528301887,0.8979554187878527,0.8245033112582781,0.9768302068302068
3,KNN,0.8577922077922079,0.8932380171100434,0.8867924528301887,0.8886851104915043,0.817451205510907,0.9635569985569985
2,LR,0.8861471861471862,0.9256220946130708,0.9245283018867925,0.920919486706486,0.8753674309229865,0.9796296296296297
2,LR,0.9004329004329005,0.9256220946130708,0.9245283018867925,0.920919486706486,0.8753674309229865,0.9842592592592593
2,LR,0.8625541125541124,0.8655806867455761,0.8679245283018868,0.863924235775925,0.7840512223515717,0.9702886002886003
2,LR,0.8577922077922077,0.8655806867455761,0.8679245283018868,0.863924235775925,0.7840512223515717,0.9735714285714286
1,SVC,0.9428571428571428,0.963162623539982,0.9622641509433962,0.9623017177418597,0.9385507246376812,0.9962962962962963
1,SVC,0.9290043290043289,1.0,1.0,1.0,1.0,0.9953703703703703
1,SVC,0.9294372294372295,1.0,1.0,1.0,1.0,1.0
1,SVC,0.9101731601731602,0.9245283018867925,0.9245283018867925,0.9245283018867925,0.8767441860465116,0.987037037037037

In [11]:
df.to_csv('Combined accuracy/With Yeo Johnson 80-20 Applying Hyperparameter BFE.csv', index=False)