In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv('Without Yeo Johnson 70-30 Applying SFS Top 4 features.csv')
df2 = pd.read_csv('Without Yeo Johnson 70-30 Applying SFS Top 5 features.csv')
df3 = pd.read_csv('Without Yeo Johnson 70-30 Applying SFS Top 7 features.csv')
df4 = pd.read_csv('Without Yeo Johnson 70-30 Applying SFS Top 9 features.csv')

In [3]:
df4

,Unnamed: 0,0,1,2,3,4,5
0,Metrics,Accuracy,Precision,Recall,F1 Score,Cohen Kappa,AUC
1,SVC,0.9125,0.919583931133429,0.9125,0.900477127039627,0.8502673796791445,0.9690782243214467
2,LR,0.95,0.9548780487804878,0.95,0.9482223186170554,0.9158559032342887,0.977738451824492
3,KNN,0.875,0.8620979532163744,0.875,0.861078431372549,0.7881355932203389,0.9355522606804284

In [4]:
df2 = df2.drop(0, axis=0)
df3 = df3.drop(0, axis=0)
df4 = df4.drop(0, axis=0)
df2

,Unnamed: 0,0,1,2,3,4,5
1,SVC,0.9125,0.9143849206349206,0.9125,0.9098057169537249,0.8533647551715109,0.963293501607534
2,LR,0.875,0.8970108695652174,0.875,0.8421570898980537,0.7809419496166484,0.9829180838130851
3,KNN,0.9,0.9043201754385966,0.9,0.9015123889668069,0.8359815479241415,0.9545851854963016

In [5]:
df = pd.concat([df1, df2, df3, df4])
df

,Unnamed: 0,0,1,2,3,4,5
0,Metrics,Accuracy,Precision,Recall,F1 Score,Cohen Kappa,AUC
1,SVC,0.9125,0.9143849206349206,0.9125,0.9098057169537249,0.8533647551715109,0.9665242839298073
2,LR,0.875,0.8970108695652174,0.875,0.8421570898980537,0.7809419496166484,0.9829180838130851
3,KNN,0.9,0.9043201754385966,0.9,0.9015123889668069,0.8359815479241415,0.9545851854963016
1,SVC,0.9125,0.9143849206349206,0.9125,0.9098057169537249,0.8533647551715109,0.963293501607534
2,LR,0.875,0.8970108695652174,0.875,0.8421570898980537,0.7809419496166484,0.9829180838130851
3,KNN,0.9,0.9043201754385966,0.9,0.9015123889668069,0.8359815479241415,0.9545851854963016
1,SVC,0.875,0.8961775362318841,0.875,0.8598762793107916,0.7834325933946941,0.9393005532749751
2,LR,0.9125,0.9264204545454545,0.9125,0.9021191578483245,0.8496644295302014,0.9892886852074637
3,KNN,0.8,0.8176785714285714,0.8,0.807427308882015,0.6762771876580678,0.8890393205209701
1,SVC,0.9125,0.919583931133429,0.9125,0.900477127039627,0.8502673796791445,0.9690782243214467
2,LR,0.95,0.9548780487804878,0.95,0.9482223186170554,0.9158559032342887,0.977738451824492
3,KNN,0.875,0.8620979532163744,0.875,0.861078431372549,0.7881355932203389,0.9355522606804284

In [6]:
df = df.drop(0, axis=0)

In [7]:
df.rename(columns={'Unnamed: 0': 'Model', '0': 'Accuracy', '1': 'Precision', '2': 'Recall', '3': 'F1 Score', '4': 'Cohen Kappa', '5': 'AUC'}, inplace=True)

In [8]:
df

,Model,Accuracy,Precision,Recall,F1 Score,Cohen Kappa,AUC
1,SVC,0.9125,0.9143849206349206,0.9125,0.9098057169537249,0.8533647551715109,0.9665242839298073
2,LR,0.875,0.8970108695652174,0.875,0.8421570898980537,0.7809419496166484,0.9829180838130851
3,KNN,0.9,0.9043201754385966,0.9,0.9015123889668069,0.8359815479241415,0.9545851854963016
1,SVC,0.9125,0.9143849206349206,0.9125,0.9098057169537249,0.8533647551715109,0.963293501607534
2,LR,0.875,0.8970108695652174,0.875,0.8421570898980537,0.7809419496166484,0.9829180838130851
3,KNN,0.9,0.9043201754385966,0.9,0.9015123889668069,0.8359815479241415,0.9545851854963016
1,SVC,0.875,0.8961775362318841,0.875,0.8598762793107916,0.7834325933946941,0.9393005532749751
2,LR,0.9125,0.9264204545454545,0.9125,0.9021191578483245,0.8496644295302014,0.9892886852074637
3,KNN,0.8,0.8176785714285714,0.8,0.807427308882015,0.6762771876580678,0.8890393205209701
1,SVC,0.9125,0.919583931133429,0.9125,0.900477127039627,0.8502673796791445,0.9690782243214467
2,LR,0.95,0.9548780487804878,0.95,0.9482223186170554,0.9158559032342887,0.977738451824492
3,KNN,0.875,0.8620979532163744,0.875,0.861078431372549,0.7881355932203389,0.9355522606804284

In [9]:
df = df.sort_values('Model')

In [10]:
df

,Model,Accuracy,Precision,Recall,F1 Score,Cohen Kappa,AUC
3,KNN,0.9,0.9043201754385966,0.9,0.9015123889668069,0.8359815479241415,0.9545851854963016
3,KNN,0.9,0.9043201754385966,0.9,0.9015123889668069,0.8359815479241415,0.9545851854963016
3,KNN,0.8,0.8176785714285714,0.8,0.807427308882015,0.6762771876580678,0.8890393205209701
3,KNN,0.875,0.8620979532163744,0.875,0.861078431372549,0.7881355932203389,0.9355522606804284
2,LR,0.875,0.8970108695652174,0.875,0.8421570898980537,0.7809419496166484,0.9829180838130851
2,LR,0.875,0.8970108695652174,0.875,0.8421570898980537,0.7809419496166484,0.9829180838130851
2,LR,0.9125,0.9264204545454545,0.9125,0.9021191578483245,0.8496644295302014,0.9892886852074637
2,LR,0.95,0.9548780487804878,0.95,0.9482223186170554,0.9158559032342887,0.977738451824492
1,SVC,0.9125,0.9143849206349206,0.9125,0.9098057169537249,0.8533647551715109,0.9665242839298073
1,SVC,0.9125,0.9143849206349206,0.9125,0.9098057169537249,0.8533647551715109,0.963293501607534
1,SVC,0.875,0.8961775362318841,0.875,0.8598762793107916,0.7834325933946941,0.9393005532749751
1,SVC,0.9125,0.919583931133429,0.9125,0.900477127039627,0.8502673796791445,0.9690782243214467

In [11]:
df.to_csv('Combined accuracy without YJ/Without Yeo Johnson 70-30 Applying SFS.csv', index=False)