In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv('With Yeo Johnson 80-20 Applying RF Top 4 features.csv')
df2 = pd.read_csv('With Yeo Johnson 80-20 Applying RF Top 5 features.csv')
df3 = pd.read_csv('With Yeo Johnson 80-20 Applying RF Top 7 features.csv')
df4 = pd.read_csv('With Yeo Johnson 80-20 Applying RF Top 9 features.csv')

In [3]:
df4

,Unnamed: 0,0,1,2,3,4,5
0,Metrics,Accuracy,Precision,Recall,F1 Score,Cohen Kappa,AUC
1,SVC,0.9433962264150944,0.9433962264150944,0.9433962264150944,0.9433962264150944,0.9075581395348837,0.9803872053872054
2,LR,0.8867924528301887,0.8878032345013478,0.8867924528301887,0.8869051532255793,0.8156521739130435,0.9492448292448293
3,KNN,0.8113207547169812,0.8260509764978484,0.8113207547169812,0.8172480409677177,0.696969696969697,0.9543915343915345

In [4]:
df2 = df2.drop(0, axis=0)
df3 = df3.drop(0, axis=0)
df4 = df4.drop(0, axis=0)
df2

,Unnamed: 0,0,1,2,3,4,5
1,SVC,0.9056603773584906,0.9152019198940748,0.9056603773584906,0.9085499705445798,0.8484848484848485,0.9812578162578163
2,LR,0.9056603773584906,0.9137466307277629,0.9056603773584906,0.9083391985418189,0.8478760045924225,0.9515728715728716
3,KNN,0.8867924528301887,0.904741905475898,0.8867924528301887,0.8919423013266111,0.8199320498301246,0.9531613756613756

In [5]:
df = pd.concat([df1, df2, df3, df4])
df

,Unnamed: 0,0,1,2,3,4,5
0,Metrics,Accuracy,Precision,Recall,F1 Score,Cohen Kappa,AUC
1,SVC,0.9245283018867925,0.9279588336192109,0.9245283018867925,0.9246406109613656,0.877456647398844,0.9845406445406445
2,LR,0.9245283018867925,0.9263252470799641,0.9245283018867925,0.925026061966434,0.8771014492753624,0.9502525252525252
3,KNN,0.9245283018867925,0.9236350835159177,0.9245283018867925,0.9226415094339623,0.8751472320376914,0.9654641654641655
1,SVC,0.9056603773584906,0.9152019198940748,0.9056603773584906,0.9085499705445798,0.8484848484848485,0.9812578162578163
2,LR,0.9056603773584906,0.9137466307277629,0.9056603773584906,0.9083391985418189,0.8478760045924225,0.9515728715728716
3,KNN,0.8867924528301887,0.904741905475898,0.8867924528301887,0.8919423013266111,0.8199320498301246,0.9531613756613756
1,SVC,0.8490566037735849,0.8722126929674099,0.8490566037735849,0.8564727756766465,0.7605872388481084,0.9673424723424725
2,LR,0.9056603773584906,0.9020664869721473,0.9056603773584906,0.9032060131922074,0.844847775175644,0.9431289081289081
3,KNN,0.8490566037735849,0.8431771252029445,0.8490566037735849,0.844895984518626,0.7502944640753828,0.962492784992785
1,SVC,0.9433962264150944,0.9433962264150944,0.9433962264150944,0.9433962264150944,0.9075581395348837,0.9803872053872054
2,LR,0.8867924528301887,0.8878032345013478,0.8867924528301887,0.8869051532255793,0.8156521739130435,0.9492448292448293
3,KNN,0.8113207547169812,0.8260509764978484,0.8113207547169812,0.8172480409677177,0.696969696969697,0.9543915343915345

In [6]:
df = df.drop(0, axis=0)

In [7]:
df.rename(columns={'Unnamed: 0': 'Model', '0': 'Accuracy', '1': 'Precision', '2': 'Recall', '3': 'F1 Score', '4': 'Cohen Kappa', '5': 'AUC'}, inplace=True)

In [8]:
df

,Model,Accuracy,Precision,Recall,F1 Score,Cohen Kappa,AUC
1,SVC,0.9245283018867925,0.9279588336192109,0.9245283018867925,0.9246406109613656,0.877456647398844,0.9845406445406445
2,LR,0.9245283018867925,0.9263252470799641,0.9245283018867925,0.925026061966434,0.8771014492753624,0.9502525252525252
3,KNN,0.9245283018867925,0.9236350835159177,0.9245283018867925,0.9226415094339623,0.8751472320376914,0.9654641654641655
1,SVC,0.9056603773584906,0.9152019198940748,0.9056603773584906,0.9085499705445798,0.8484848484848485,0.9812578162578163
2,LR,0.9056603773584906,0.9137466307277629,0.9056603773584906,0.9083391985418189,0.8478760045924225,0.9515728715728716
3,KNN,0.8867924528301887,0.904741905475898,0.8867924528301887,0.8919423013266111,0.8199320498301246,0.9531613756613756
1,SVC,0.8490566037735849,0.8722126929674099,0.8490566037735849,0.8564727756766465,0.7605872388481084,0.9673424723424725
2,LR,0.9056603773584906,0.9020664869721473,0.9056603773584906,0.9032060131922074,0.844847775175644,0.9431289081289081
3,KNN,0.8490566037735849,0.8431771252029445,0.8490566037735849,0.844895984518626,0.7502944640753828,0.962492784992785
1,SVC,0.9433962264150944,0.9433962264150944,0.9433962264150944,0.9433962264150944,0.9075581395348837,0.9803872053872054
2,LR,0.8867924528301887,0.8878032345013478,0.8867924528301887,0.8869051532255793,0.8156521739130435,0.9492448292448293
3,KNN,0.8113207547169812,0.8260509764978484,0.8113207547169812,0.8172480409677177,0.696969696969697,0.9543915343915345

In [9]:
df = df.sort_values('Model')

In [10]:
df

,Model,Accuracy,Precision,Recall,F1 Score,Cohen Kappa,AUC
3,KNN,0.9245283018867925,0.9236350835159177,0.9245283018867925,0.9226415094339623,0.8751472320376914,0.9654641654641655
3,KNN,0.8867924528301887,0.904741905475898,0.8867924528301887,0.8919423013266111,0.8199320498301246,0.9531613756613756
3,KNN,0.8490566037735849,0.8431771252029445,0.8490566037735849,0.844895984518626,0.7502944640753828,0.962492784992785
3,KNN,0.8113207547169812,0.8260509764978484,0.8113207547169812,0.8172480409677177,0.696969696969697,0.9543915343915345
2,LR,0.9245283018867925,0.9263252470799641,0.9245283018867925,0.925026061966434,0.8771014492753624,0.9502525252525252
2,LR,0.9056603773584906,0.9137466307277629,0.9056603773584906,0.9083391985418189,0.8478760045924225,0.9515728715728716
2,LR,0.9056603773584906,0.9020664869721473,0.9056603773584906,0.9032060131922074,0.844847775175644,0.9431289081289081
2,LR,0.8867924528301887,0.8878032345013478,0.8867924528301887,0.8869051532255793,0.8156521739130435,0.9492448292448293
1,SVC,0.9245283018867925,0.9279588336192109,0.9245283018867925,0.9246406109613656,0.877456647398844,0.9845406445406445
1,SVC,0.9056603773584906,0.9152019198940748,0.9056603773584906,0.9085499705445798,0.8484848484848485,0.9812578162578163
1,SVC,0.8490566037735849,0.8722126929674099,0.8490566037735849,0.8564727756766465,0.7605872388481084,0.9673424723424725
1,SVC,0.9433962264150944,0.9433962264150944,0.9433962264150944,0.9433962264150944,0.9075581395348837,0.9803872053872054

In [11]:
df.to_csv('Combined accuracy/With Yeo Johnson 80-20 Applying RF.csv', index=False)