In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv('Without Yeo Johnson 80-20 Applying SFS Top 4 features.csv')
df2 = pd.read_csv('Without Yeo Johnson 80-20 Applying SFS Top 5 features.csv')
df3 = pd.read_csv('Without Yeo Johnson 80-20 Applying SFS Top 7 features.csv')
df4 = pd.read_csv('Without Yeo Johnson 80-20 Applying SFS Top 9 features.csv')

In [3]:
df4

,Unnamed: 0,0,1,2,3,4,5
0,Metrics,Accuracy,Precision,Recall,F1 Score,Cohen Kappa,AUC
1,SVC,0.9056603773584906,0.9054153393776035,0.9056603773584906,0.9041201386214863,0.8453006421482778,0.949944684944685
2,LR,0.9056603773584906,0.9054153393776035,0.9056603773584906,0.9041201386214863,0.8453006421482778,0.9541534391534392
3,KNN,0.8679245283018868,0.859538784067086,0.8679245283018868,0.861289653742484,0.7799525504151839,0.9452525252525251

In [4]:
df2 = df2.drop(0, axis=0)
df3 = df3.drop(0, axis=0)
df4 = df4.drop(0, axis=0)
df2

,Unnamed: 0,0,1,2,3,4,5
1,SVC,0.8867924528301887,0.8941755537325676,0.8867924528301887,0.8869604996592384,0.8167146974063401,0.9781746031746031
2,LR,0.9245283018867925,0.9326370921941062,0.9245283018867925,0.9141092154281634,0.8728254349130173,0.9884126984126983
3,KNN,0.8301886792452831,0.8827838827838828,0.8301886792452831,0.843375906192289,0.7364640883977901,0.9678499278499278

In [5]:
df = pd.concat([df1, df2, df3, df4])
df

,Unnamed: 0,0,1,2,3,4,5
0,Metrics,Accuracy,Precision,Recall,F1 Score,Cohen Kappa,AUC
1,SVC,0.9056603773584906,0.910377358490566,0.9056603773584906,0.9074724229314368,0.8474381116868164,0.986957671957672
2,LR,0.8867924528301887,0.8767590080141351,0.8867924528301887,0.8704540174999355,0.8092381523695261,0.9898148148148148
3,KNN,0.9811320754716981,0.9832285115303984,0.9811320754716981,0.9814944845862873,0.9694876223373633,0.9990608465608467
1,SVC,0.8867924528301887,0.8941755537325676,0.8867924528301887,0.8869604996592384,0.8167146974063401,0.9781746031746031
2,LR,0.9245283018867925,0.9326370921941062,0.9245283018867925,0.9141092154281634,0.8728254349130173,0.9884126984126983
3,KNN,0.8301886792452831,0.8827838827838828,0.8301886792452831,0.843375906192289,0.7364640883977901,0.9678499278499278
1,SVC,0.8679245283018868,0.8616352201257863,0.8679245283018868,0.8524871355060034,0.77811004784689,0.9495262145262146
2,LR,0.8867924528301887,0.9056603773584906,0.8867924528301887,0.8705927196493235,0.808433734939759,0.9860582010582011
3,KNN,0.7924528301886793,0.7757861635220125,0.7924528301886793,0.7787576305096521,0.654825340438129,0.9213407888407888
1,SVC,0.9056603773584906,0.9054153393776035,0.9056603773584906,0.9041201386214863,0.8453006421482778,0.949944684944685
2,LR,0.9056603773584906,0.9054153393776035,0.9056603773584906,0.9041201386214863,0.8453006421482778,0.9541534391534392
3,KNN,0.8679245283018868,0.859538784067086,0.8679245283018868,0.861289653742484,0.7799525504151839,0.9452525252525251

In [6]:
df = df.drop(0, axis=0)

In [7]:
df.rename(columns={'Unnamed: 0': 'Model', '0': 'Accuracy', '1': 'Precision', '2': 'Recall', '3': 'F1 Score', '4': 'Cohen Kappa', '5': 'AUC'}, inplace=True)

In [8]:
df

,Model,Accuracy,Precision,Recall,F1 Score,Cohen Kappa,AUC
1,SVC,0.9056603773584906,0.910377358490566,0.9056603773584906,0.9074724229314368,0.8474381116868164,0.986957671957672
2,LR,0.8867924528301887,0.8767590080141351,0.8867924528301887,0.8704540174999355,0.8092381523695261,0.9898148148148148
3,KNN,0.9811320754716981,0.9832285115303984,0.9811320754716981,0.9814944845862873,0.9694876223373633,0.9990608465608467
1,SVC,0.8867924528301887,0.8941755537325676,0.8867924528301887,0.8869604996592384,0.8167146974063401,0.9781746031746031
2,LR,0.9245283018867925,0.9326370921941062,0.9245283018867925,0.9141092154281634,0.8728254349130173,0.9884126984126983
3,KNN,0.8301886792452831,0.8827838827838828,0.8301886792452831,0.843375906192289,0.7364640883977901,0.9678499278499278
1,SVC,0.8679245283018868,0.8616352201257863,0.8679245283018868,0.8524871355060034,0.77811004784689,0.9495262145262146
2,LR,0.8867924528301887,0.9056603773584906,0.8867924528301887,0.8705927196493235,0.808433734939759,0.9860582010582011
3,KNN,0.7924528301886793,0.7757861635220125,0.7924528301886793,0.7787576305096521,0.654825340438129,0.9213407888407888
1,SVC,0.9056603773584906,0.9054153393776035,0.9056603773584906,0.9041201386214863,0.8453006421482778,0.949944684944685
2,LR,0.9056603773584906,0.9054153393776035,0.9056603773584906,0.9041201386214863,0.8453006421482778,0.9541534391534392
3,KNN,0.8679245283018868,0.859538784067086,0.8679245283018868,0.861289653742484,0.7799525504151839,0.9452525252525251

In [9]:
df = df.sort_values('Model')

In [10]:
df

,Model,Accuracy,Precision,Recall,F1 Score,Cohen Kappa,AUC
3,KNN,0.9811320754716981,0.9832285115303984,0.9811320754716981,0.9814944845862873,0.9694876223373633,0.9990608465608467
3,KNN,0.8301886792452831,0.8827838827838828,0.8301886792452831,0.843375906192289,0.7364640883977901,0.9678499278499278
3,KNN,0.7924528301886793,0.7757861635220125,0.7924528301886793,0.7787576305096521,0.654825340438129,0.9213407888407888
3,KNN,0.8679245283018868,0.859538784067086,0.8679245283018868,0.861289653742484,0.7799525504151839,0.9452525252525251
2,LR,0.8867924528301887,0.8767590080141351,0.8867924528301887,0.8704540174999355,0.8092381523695261,0.9898148148148148
2,LR,0.9245283018867925,0.9326370921941062,0.9245283018867925,0.9141092154281634,0.8728254349130173,0.9884126984126983
2,LR,0.8867924528301887,0.9056603773584906,0.8867924528301887,0.8705927196493235,0.808433734939759,0.9860582010582011
2,LR,0.9056603773584906,0.9054153393776035,0.9056603773584906,0.9041201386214863,0.8453006421482778,0.9541534391534392
1,SVC,0.9056603773584906,0.910377358490566,0.9056603773584906,0.9074724229314368,0.8474381116868164,0.986957671957672
1,SVC,0.8867924528301887,0.8941755537325676,0.8867924528301887,0.8869604996592384,0.8167146974063401,0.9781746031746031
1,SVC,0.8679245283018868,0.8616352201257863,0.8679245283018868,0.8524871355060034,0.77811004784689,0.9495262145262146
1,SVC,0.9056603773584906,0.9054153393776035,0.9056603773584906,0.9041201386214863,0.8453006421482778,0.949944684944685

In [11]:
df.to_csv('Combined accuracy without YJ/Without Yeo Johnson 80-20 Applying SFS.csv', index=False)