In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv('Without Yeo Johnson 70-30 Applying Hyperparameter SFS Top 4 features.csv')
df2 = pd.read_csv('Without Yeo Johnson 70-30 Applying Hyperparameter SFS Top 5 features.csv')
df3 = pd.read_csv('Without Yeo Johnson 70-30 Applying Hyperparameter SFS Top 7 features.csv')
df4 = pd.read_csv('Without Yeo Johnson 70-30 Applying Hyperparameter SFS Top 9 features.csv')

In [3]:
df4

,Unnamed: 0,0,1,2,3,4,5
0,Metrics,Accuracy,Precision,Recall,F1 Score,Cohen Kappa,AUC
1,SVC,0.9236842105263158,0.9762820512820513,0.975,0.9740789473684209,0.9582681272822118,0.9947828577540566
2,LR,0.884795321637427,0.9515625,0.95,0.9494344365312107,0.9168831168831169,0.98015133747447
3,KNN,0.8690058479532163,0.8990129662004662,0.9,0.8965334008097166,0.8321531602412798,0.9747935087154785

In [4]:
df2 = df2.drop(0, axis=0)
df3 = df3.drop(0, axis=0)
df4 = df4.drop(0, axis=0)
df2

,Unnamed: 0,0,1,2,3,4,5
1,SVC,0.9342105263157896,0.951923076923077,0.95,0.9494078947368422,0.9165362545644236,0.995863216244441
2,LR,0.8736842105263157,0.9449404761904763,0.9375,0.9338230861965038,0.894095843261848,0.9918984340689504
3,KNN,0.867543859649123,0.9377698511166253,0.9375,0.9369674185463659,0.8962386511024644,0.9868903680400457

In [5]:
df = pd.concat([df1, df2, df3, df4])
df

,Unnamed: 0,0,1,2,3,4,5
0,Metrics,Accuracy,Precision,Recall,F1 Score,Cohen Kappa,AUC
1,SVC,0.9342105263157896,0.951923076923077,0.95,0.9494078947368422,0.9165362545644236,0.995863216244441
2,LR,0.8736842105263157,0.9449404761904763,0.9375,0.9338230861965038,0.894095843261848,0.9918984340689504
3,KNN,0.867543859649123,0.9377698511166253,0.9375,0.9369674185463659,0.8962386511024644,0.9868903680400457
1,SVC,0.9342105263157896,0.951923076923077,0.95,0.9494078947368422,0.9165362545644236,0.995863216244441
2,LR,0.8736842105263157,0.9449404761904763,0.9375,0.9338230861965038,0.894095843261848,0.9918984340689504
3,KNN,0.867543859649123,0.9377698511166253,0.9375,0.9369674185463659,0.8962386511024644,0.9868903680400457
1,SVC,0.923391812865497,0.9878289473684211,0.9875,0.9872857142857143,0.9792746113989638,0.9989247880840556
2,LR,0.8631578947368421,0.9354651162790697,0.925,0.9185221171802052,0.8720341242335377,0.995194814997804
3,KNN,0.8245614035087719,0.9102351916376307,0.9125,0.9054487179487178,0.85193019566367,0.9634963826342428
1,SVC,0.9236842105263158,0.9762820512820513,0.975,0.9740789473684209,0.9582681272822118,0.9947828577540566
2,LR,0.884795321637427,0.9515625,0.95,0.9494344365312107,0.9168831168831169,0.98015133747447
3,KNN,0.8690058479532163,0.8990129662004662,0.9,0.8965334008097166,0.8321531602412798,0.9747935087154785

In [6]:
df = df.drop(0, axis=0)

In [7]:
df.rename(columns={'Unnamed: 0': 'Model', '0': 'Accuracy', '1': 'Precision', '2': 'Recall', '3': 'F1 Score', '4': 'Cohen Kappa', '5': 'AUC'}, inplace=True)

In [8]:
df

,Model,Accuracy,Precision,Recall,F1 Score,Cohen Kappa,AUC
1,SVC,0.9342105263157896,0.951923076923077,0.95,0.9494078947368422,0.9165362545644236,0.995863216244441
2,LR,0.8736842105263157,0.9449404761904763,0.9375,0.9338230861965038,0.894095843261848,0.9918984340689504
3,KNN,0.867543859649123,0.9377698511166253,0.9375,0.9369674185463659,0.8962386511024644,0.9868903680400457
1,SVC,0.9342105263157896,0.951923076923077,0.95,0.9494078947368422,0.9165362545644236,0.995863216244441
2,LR,0.8736842105263157,0.9449404761904763,0.9375,0.9338230861965038,0.894095843261848,0.9918984340689504
3,KNN,0.867543859649123,0.9377698511166253,0.9375,0.9369674185463659,0.8962386511024644,0.9868903680400457
1,SVC,0.923391812865497,0.9878289473684211,0.9875,0.9872857142857143,0.9792746113989638,0.9989247880840556
2,LR,0.8631578947368421,0.9354651162790697,0.925,0.9185221171802052,0.8720341242335377,0.995194814997804
3,KNN,0.8245614035087719,0.9102351916376307,0.9125,0.9054487179487178,0.85193019566367,0.9634963826342428
1,SVC,0.9236842105263158,0.9762820512820513,0.975,0.9740789473684209,0.9582681272822118,0.9947828577540566
2,LR,0.884795321637427,0.9515625,0.95,0.9494344365312107,0.9168831168831169,0.98015133747447
3,KNN,0.8690058479532163,0.8990129662004662,0.9,0.8965334008097166,0.8321531602412798,0.9747935087154785

In [9]:
df = df.sort_values('Model')

In [10]:
df

,Model,Accuracy,Precision,Recall,F1 Score,Cohen Kappa,AUC
3,KNN,0.867543859649123,0.9377698511166253,0.9375,0.9369674185463659,0.8962386511024644,0.9868903680400457
3,KNN,0.867543859649123,0.9377698511166253,0.9375,0.9369674185463659,0.8962386511024644,0.9868903680400457
3,KNN,0.8245614035087719,0.9102351916376307,0.9125,0.9054487179487178,0.85193019566367,0.9634963826342428
3,KNN,0.8690058479532163,0.8990129662004662,0.9,0.8965334008097166,0.8321531602412798,0.9747935087154785
2,LR,0.8736842105263157,0.9449404761904763,0.9375,0.9338230861965038,0.894095843261848,0.9918984340689504
2,LR,0.8736842105263157,0.9449404761904763,0.9375,0.9338230861965038,0.894095843261848,0.9918984340689504
2,LR,0.8631578947368421,0.9354651162790697,0.925,0.9185221171802052,0.8720341242335377,0.995194814997804
2,LR,0.884795321637427,0.9515625,0.95,0.9494344365312107,0.9168831168831169,0.98015133747447
1,SVC,0.9342105263157896,0.951923076923077,0.95,0.9494078947368422,0.9165362545644236,0.995863216244441
1,SVC,0.9342105263157896,0.951923076923077,0.95,0.9494078947368422,0.9165362545644236,0.995863216244441
1,SVC,0.923391812865497,0.9878289473684211,0.9875,0.9872857142857143,0.9792746113989638,0.9989247880840556
1,SVC,0.9236842105263158,0.9762820512820513,0.975,0.9740789473684209,0.9582681272822118,0.9947828577540566

In [11]:
df.to_csv('Combined accuracy without YJ/Without Yeo Johnson 70-30 Applying Hyperparameter SFS.csv', index=False)