In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv('Without Yeo Johnson 70-30 Applying Hyperparameter RF Top 4 features.csv')
df2 = pd.read_csv('Without Yeo Johnson 70-30 Applying Hyperparameter RF Top 5 features.csv')
df3 = pd.read_csv('Without Yeo Johnson 70-30 Applying Hyperparameter RF Top 7 features.csv')
df4 = pd.read_csv('Without Yeo Johnson 70-30 Applying Hyperparameter RF Top 9 features.csv')

In [3]:
df4

,Unnamed: 0,0,1,2,3,4,5
0,Metrics,Accuracy,Precision,Recall,F1 Score,Cohen Kappa,AUC
1,SVC,0.9194805194805195,0.9358490566037736,0.9245283018867925,0.9279350104821803,0.879133409350057,0.979939874939875
2,LR,0.9002164502164502,0.9263252470799641,0.9245283018867925,0.925026061966434,0.8771014492753624,0.9592616642616644
3,KNN,0.901082251082251,0.9153404429860541,0.9056603773584906,0.9082809224318658,0.8489167616875712,0.9849422799422799

In [4]:
df2 = df2.drop(0, axis=0)
df3 = df3.drop(0, axis=0)
df4 = df4.drop(0, axis=0)
df2

,Unnamed: 0,0,1,2,3,4,5
1,SVC,0.9430735930735932,0.9468267581475128,0.9433962264150944,0.9435085354896675,0.908092485549133,0.9958201058201058
2,LR,0.9142857142857144,0.9424977538185084,0.9433962264150944,0.9421997238840313,0.9069086651053864,0.9681818181818183
3,KNN,0.9244588744588744,0.9169811320754717,0.9056603773584906,0.9088602008165068,0.8480504587155964,0.9888239538239537

In [5]:
df = pd.concat([df1, df2, df3, df4])
df

,Unnamed: 0,0,1,2,3,4,5
0,Metrics,Accuracy,Precision,Recall,F1 Score,Cohen Kappa,AUC
1,SVC,0.9571428571428571,0.9424977538185084,0.9433962264150944,0.9421997238840313,0.9069086651053864,0.9877946127946129
2,LR,0.9142857142857144,0.9263252470799641,0.9245283018867925,0.925026061966434,0.8771014492753624,0.9682659932659932
3,KNN,0.9385281385281387,0.9236298292902065,0.9245283018867925,0.9233317993557294,0.8758782201405152,0.9841221741221742
1,SVC,0.9430735930735932,0.9468267581475128,0.9433962264150944,0.9435085354896675,0.908092485549133,0.9958201058201058
2,LR,0.9142857142857144,0.9424977538185084,0.9433962264150944,0.9421997238840313,0.9069086651053864,0.9681818181818183
3,KNN,0.9244588744588744,0.9169811320754717,0.9056603773584906,0.9088602008165068,0.8480504587155964,0.9888239538239537
1,SVC,0.9430735930735932,0.9484875711290804,0.9433962264150944,0.9445049764038151,0.9087256027554536,0.9897041847041846
2,LR,0.9142857142857144,0.9263252470799641,0.9245283018867925,0.925026061966434,0.8771014492753624,0.9597113997113998
3,KNN,0.9387445887445887,0.9279350104821803,0.9245283018867925,0.9256155292305601,0.8779504893494531,0.9873232323232323
1,SVC,0.9194805194805195,0.9358490566037736,0.9245283018867925,0.9279350104821803,0.879133409350057,0.979939874939875
2,LR,0.9002164502164502,0.9263252470799641,0.9245283018867925,0.925026061966434,0.8771014492753624,0.9592616642616644
3,KNN,0.901082251082251,0.9153404429860541,0.9056603773584906,0.9082809224318658,0.8489167616875712,0.9849422799422799

In [6]:
df = df.drop(0, axis=0)

In [7]:
df.rename(columns={'Unnamed: 0': 'Model', '0': 'Accuracy', '1': 'Precision', '2': 'Recall', '3': 'F1 Score', '4': 'Cohen Kappa', '5': 'AUC'}, inplace=True)

In [8]:
df

,Model,Accuracy,Precision,Recall,F1 Score,Cohen Kappa,AUC
1,SVC,0.9571428571428571,0.9424977538185084,0.9433962264150944,0.9421997238840313,0.9069086651053864,0.9877946127946129
2,LR,0.9142857142857144,0.9263252470799641,0.9245283018867925,0.925026061966434,0.8771014492753624,0.9682659932659932
3,KNN,0.9385281385281387,0.9236298292902065,0.9245283018867925,0.9233317993557294,0.8758782201405152,0.9841221741221742
1,SVC,0.9430735930735932,0.9468267581475128,0.9433962264150944,0.9435085354896675,0.908092485549133,0.9958201058201058
2,LR,0.9142857142857144,0.9424977538185084,0.9433962264150944,0.9421997238840313,0.9069086651053864,0.9681818181818183
3,KNN,0.9244588744588744,0.9169811320754717,0.9056603773584906,0.9088602008165068,0.8480504587155964,0.9888239538239537
1,SVC,0.9430735930735932,0.9484875711290804,0.9433962264150944,0.9445049764038151,0.9087256027554536,0.9897041847041846
2,LR,0.9142857142857144,0.9263252470799641,0.9245283018867925,0.925026061966434,0.8771014492753624,0.9597113997113998
3,KNN,0.9387445887445887,0.9279350104821803,0.9245283018867925,0.9256155292305601,0.8779504893494531,0.9873232323232323
1,SVC,0.9194805194805195,0.9358490566037736,0.9245283018867925,0.9279350104821803,0.879133409350057,0.979939874939875
2,LR,0.9002164502164502,0.9263252470799641,0.9245283018867925,0.925026061966434,0.8771014492753624,0.9592616642616644
3,KNN,0.901082251082251,0.9153404429860541,0.9056603773584906,0.9082809224318658,0.8489167616875712,0.9849422799422799

In [9]:
df = df.sort_values('Model')

In [10]:
df

,Model,Accuracy,Precision,Recall,F1 Score,Cohen Kappa,AUC
3,KNN,0.9385281385281387,0.9236298292902065,0.9245283018867925,0.9233317993557294,0.8758782201405152,0.9841221741221742
3,KNN,0.9244588744588744,0.9169811320754717,0.9056603773584906,0.9088602008165068,0.8480504587155964,0.9888239538239537
3,KNN,0.9387445887445887,0.9279350104821803,0.9245283018867925,0.9256155292305601,0.8779504893494531,0.9873232323232323
3,KNN,0.901082251082251,0.9153404429860541,0.9056603773584906,0.9082809224318658,0.8489167616875712,0.9849422799422799
2,LR,0.9142857142857144,0.9263252470799641,0.9245283018867925,0.925026061966434,0.8771014492753624,0.9682659932659932
2,LR,0.9142857142857144,0.9424977538185084,0.9433962264150944,0.9421997238840313,0.9069086651053864,0.9681818181818183
2,LR,0.9142857142857144,0.9263252470799641,0.9245283018867925,0.925026061966434,0.8771014492753624,0.9597113997113998
2,LR,0.9002164502164502,0.9263252470799641,0.9245283018867925,0.925026061966434,0.8771014492753624,0.9592616642616644
1,SVC,0.9571428571428571,0.9424977538185084,0.9433962264150944,0.9421997238840313,0.9069086651053864,0.9877946127946129
1,SVC,0.9430735930735932,0.9468267581475128,0.9433962264150944,0.9435085354896675,0.908092485549133,0.9958201058201058
1,SVC,0.9430735930735932,0.9484875711290804,0.9433962264150944,0.9445049764038151,0.9087256027554536,0.9897041847041846
1,SVC,0.9194805194805195,0.9358490566037736,0.9245283018867925,0.9279350104821803,0.879133409350057,0.979939874939875

In [11]:
df.to_csv('Combined accuracy without YJ/Without Yeo Johnson 70-30 Applying Hyperparameter RF.csv', index=False)