In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv('LMCH Extremely Imbalance 80-20 Applying IG Top 4 features.csv')
df2 = pd.read_csv('LMCH Extremely Imbalance 80-20 Applying IG Top 5 features.csv')
df3 = pd.read_csv('LMCH Extremely Imbalance 80-20 Applying IG Top 7 features.csv')
df4 = pd.read_csv('LMCH Extremely Imbalance 80-20 Applying IG Top 9 features.csv')

In [3]:
df4

,Unnamed: 0,0,1,2,3,4,5
0,Metrics,Accuracy,Precision,Recall,F1 Score,Cohen Kappa,AUC
1,SVC,0.9397590361445783,0.9456101432758058,0.9397590361445783,0.9360079711012371,0.7025089605734767,0.9678581700336455
2,LR,0.9156626506024096,0.9036600949251551,0.9156626506024096,0.9057685824298668,0.6191412651589643,0.9744423686028617
3,KNN,0.9397590361445783,0.9496341530505583,0.9397590361445783,0.9370431190798645,0.716142270861833,0.9359262781248353

In [4]:
df2 = df2.drop(0, axis=0)
df3 = df3.drop(0, axis=0)
df4 = df4.drop(0, axis=0)
df2

,Unnamed: 0,0,1,2,3,4,5
1,SVC,0.9457831325301205,0.9639737772267892,0.9457831325301205,0.9451795009653217,0.76096,0.991605400594786
2,LR,0.9216867469879518,0.9418387837062534,0.9216867469879518,0.9176750317565854,0.6467506956948764,0.9802437427962638
3,KNN,0.9397590361445783,0.9563755020080322,0.9397590361445783,0.9392678492790282,0.7285807717462394,0.9594621198681903

In [5]:
df = pd.concat([df1, df2, df3, df4])
df

,Unnamed: 0,0,1,2,3,4,5
0,Metrics,Accuracy,Precision,Recall,F1 Score,Cohen Kappa,AUC
1,SVC,0.9457831325301205,0.9639737772267892,0.9457831325301205,0.9451795009653217,0.76096,0.9912689941023644
2,LR,0.9156626506024096,0.9036600949251551,0.9156626506024096,0.9057685824298668,0.6191412651589643,0.979132202251121
3,KNN,0.9397590361445783,0.9468003593320652,0.9397590361445783,0.9390396638098787,0.7288910664706842,0.985850393913751
1,SVC,0.9457831325301205,0.9639737772267892,0.9457831325301205,0.9451795009653217,0.76096,0.991605400594786
2,LR,0.9216867469879518,0.9418387837062534,0.9216867469879518,0.9176750317565854,0.6467506956948764,0.9802437427962638
3,KNN,0.9397590361445783,0.9563755020080322,0.9397590361445783,0.9392678492790282,0.7285807717462394,0.9594621198681903
1,SVC,0.9337349397590361,0.9597145471045235,0.9337349397590361,0.9309796443973289,0.7136584600909519,0.985991955824165
2,LR,0.9156626506024096,0.9056942053930005,0.9156626506024096,0.9073480093813704,0.6195776722867901,0.9745242878977951
3,KNN,0.9578313253012049,0.972590361445783,0.9578313253012049,0.961653431909456,0.8222969873069277,0.9899694026283478
1,SVC,0.9397590361445783,0.9456101432758058,0.9397590361445783,0.9360079711012371,0.7025089605734767,0.9678581700336455
2,LR,0.9156626506024096,0.9036600949251551,0.9156626506024096,0.9057685824298668,0.6191412651589643,0.9744423686028617
3,KNN,0.9397590361445783,0.9496341530505583,0.9397590361445783,0.9370431190798645,0.716142270861833,0.9359262781248353

In [6]:
df = df.drop(0, axis=0)

In [7]:
df.rename(columns={'Unnamed: 0': 'Model', '0': 'Accuracy', '1': 'Precision', '2': 'Recall', '3': 'F1 Score', '4': 'Cohen Kappa', '5': 'AUC'}, inplace=True)

In [8]:
df

,Model,Accuracy,Precision,Recall,F1 Score,Cohen Kappa,AUC
1,SVC,0.9457831325301205,0.9639737772267892,0.9457831325301205,0.9451795009653217,0.76096,0.9912689941023644
2,LR,0.9156626506024096,0.9036600949251551,0.9156626506024096,0.9057685824298668,0.6191412651589643,0.979132202251121
3,KNN,0.9397590361445783,0.9468003593320652,0.9397590361445783,0.9390396638098787,0.7288910664706842,0.985850393913751
1,SVC,0.9457831325301205,0.9639737772267892,0.9457831325301205,0.9451795009653217,0.76096,0.991605400594786
2,LR,0.9216867469879518,0.9418387837062534,0.9216867469879518,0.9176750317565854,0.6467506956948764,0.9802437427962638
3,KNN,0.9397590361445783,0.9563755020080322,0.9397590361445783,0.9392678492790282,0.7285807717462394,0.9594621198681903
1,SVC,0.9337349397590361,0.9597145471045235,0.9337349397590361,0.9309796443973289,0.7136584600909519,0.985991955824165
2,LR,0.9156626506024096,0.9056942053930005,0.9156626506024096,0.9073480093813704,0.6195776722867901,0.9745242878977951
3,KNN,0.9578313253012049,0.972590361445783,0.9578313253012049,0.961653431909456,0.8222969873069277,0.9899694026283478
1,SVC,0.9397590361445783,0.9456101432758058,0.9397590361445783,0.9360079711012371,0.7025089605734767,0.9678581700336455
2,LR,0.9156626506024096,0.9036600949251551,0.9156626506024096,0.9057685824298668,0.6191412651589643,0.9744423686028617
3,KNN,0.9397590361445783,0.9496341530505583,0.9397590361445783,0.9370431190798645,0.716142270861833,0.9359262781248353

In [9]:
df = df.sort_values('Model')

In [10]:
df

,Model,Accuracy,Precision,Recall,F1 Score,Cohen Kappa,AUC
3,KNN,0.9397590361445783,0.9468003593320652,0.9397590361445783,0.9390396638098787,0.7288910664706842,0.985850393913751
3,KNN,0.9397590361445783,0.9563755020080322,0.9397590361445783,0.9392678492790282,0.7285807717462394,0.9594621198681903
3,KNN,0.9578313253012049,0.972590361445783,0.9578313253012049,0.961653431909456,0.8222969873069277,0.9899694026283478
3,KNN,0.9397590361445783,0.9496341530505583,0.9397590361445783,0.9370431190798645,0.716142270861833,0.9359262781248353
2,LR,0.9156626506024096,0.9036600949251551,0.9156626506024096,0.9057685824298668,0.6191412651589643,0.979132202251121
2,LR,0.9216867469879518,0.9418387837062534,0.9216867469879518,0.9176750317565854,0.6467506956948764,0.9802437427962638
2,LR,0.9156626506024096,0.9056942053930005,0.9156626506024096,0.9073480093813704,0.6195776722867901,0.9745242878977951
2,LR,0.9156626506024096,0.9036600949251551,0.9156626506024096,0.9057685824298668,0.6191412651589643,0.9744423686028617
1,SVC,0.9457831325301205,0.9639737772267892,0.9457831325301205,0.9451795009653217,0.76096,0.9912689941023644
1,SVC,0.9457831325301205,0.9639737772267892,0.9457831325301205,0.9451795009653217,0.76096,0.991605400594786
1,SVC,0.9337349397590361,0.9597145471045235,0.9337349397590361,0.9309796443973289,0.7136584600909519,0.985991955824165
1,SVC,0.9397590361445783,0.9456101432758058,0.9397590361445783,0.9360079711012371,0.7025089605734767,0.9678581700336455

In [11]:
df.to_csv('LMCH EI 80-20 Applying IG.csv', index=False)