In [12]:
import pandas as pd

In [13]:
df1 = pd.read_csv('Without Yeo Johnson 70-30 Applying Hyperparameter IG Top 4 features.csv')
df2 = pd.read_csv('Without Yeo Johnson 70-30 Applying Hyperparameter IG Top 5 features.csv')
df3 = pd.read_csv('Without Yeo Johnson 70-30 Applying Hyperparameter IG Top 7 features.csv')
df4 = pd.read_csv('Without Yeo Johnson 70-30 Applying Hyperparameter IG Top 9 features.csv')

In [14]:
df4

,Unnamed: 0,0,1,2,3,4,5
0,Metrics,Accuracy,Precision,Recall,F1 Score,Cohen Kappa,AUC
1,SVC,0.9376890502117362,0.9549396448729041,0.9475806451612904,0.9470534928131183,0.7651515151515151,0.9638597608051601
2,LR,0.9135511191772535,0.9370061265316328,0.9395161290322581,0.9358399550757008,0.7328162034044388,0.9760133137237909
3,KNN,0.9412280701754387,0.9646057347670252,0.9596774193548387,0.9597324692813461,0.8195576251455181,0.9902107624305637

In [15]:
df2 = df2.drop(0, axis=0)
df3 = df3.drop(0, axis=0)
df4 = df4.drop(0, axis=0)
df2

,Unnamed: 0,0,1,2,3,4,5
1,SVC,0.9447065940713854,0.9761077122728958,0.9717741935483871,0.9725877698007404,0.8791170531300049,0.9956644687154611
2,LR,0.904930429522081,0.9245061265316329,0.9395161290322581,0.9295698481284789,0.7318918918918919,0.9694566765013001
3,KNN,0.9343617664851784,0.9700124927102034,0.967741935483871,0.9679015043169659,0.8537412458532989,0.9946164621253294

In [16]:
df = pd.concat([df1, df2, df3, df4])
df

,Unnamed: 0,0,1,2,3,4,5
0,Metrics,Accuracy,Precision,Recall,F1 Score,Cohen Kappa,AUC
1,SVC,0.9481851179673322,0.9742525876796302,0.967741935483871,0.9678443365486884,0.859629262770624,0.9949207267839908
2,LR,0.9066545674531156,0.9348355328204978,0.9354838709677419,0.9323924731182796,0.7189403598243377,0.9806116454904993
3,KNN,0.9309134906231094,0.9672381613068397,0.9637096774193549,0.9633179964270063,0.8352645951730755,0.9926904803983257
1,SVC,0.9447065940713854,0.9761077122728958,0.9717741935483871,0.9725877698007404,0.8791170531300049,0.9956644687154611
2,LR,0.904930429522081,0.9245061265316329,0.9395161290322581,0.9295698481284789,0.7318918918918919,0.9694566765013001
3,KNN,0.9343617664851784,0.9700124927102034,0.967741935483871,0.9679015043169659,0.8537412458532989,0.9946164621253294
1,SVC,0.9429824561403508,0.9711419051946086,0.9637096774193549,0.9652704423698185,0.8444057162774485,0.9893704541157731
2,LR,0.9187840290381126,0.9370061265316328,0.9395161290322581,0.9358399550757008,0.7328162034044388,0.9756532382669324
3,KNN,0.9360556563823353,0.9629923105776443,0.9596774193548387,0.9600144907847665,0.8222859190254389,0.9933512420464309
1,SVC,0.9376890502117362,0.9549396448729041,0.9475806451612904,0.9470534928131183,0.7651515151515151,0.9638597608051601
2,LR,0.9135511191772535,0.9370061265316328,0.9395161290322581,0.9358399550757008,0.7328162034044388,0.9760133137237909
3,KNN,0.9412280701754387,0.9646057347670252,0.9596774193548387,0.9597324692813461,0.8195576251455181,0.9902107624305637

In [17]:
df = df.drop(0, axis=0)

In [18]:
df.rename(columns={'Unnamed: 0': 'Model', '0': 'Accuracy', '1': 'Precision', '2': 'Recall', '3': 'F1 Score', '4': 'Cohen Kappa', '5': 'AUC'}, inplace=True)

In [19]:
df

,Model,Accuracy,Precision,Recall,F1 Score,Cohen Kappa,AUC
1,SVC,0.9481851179673322,0.9742525876796302,0.967741935483871,0.9678443365486884,0.859629262770624,0.9949207267839908
2,LR,0.9066545674531156,0.9348355328204978,0.9354838709677419,0.9323924731182796,0.7189403598243377,0.9806116454904993
3,KNN,0.9309134906231094,0.9672381613068397,0.9637096774193549,0.9633179964270063,0.8352645951730755,0.9926904803983257
1,SVC,0.9447065940713854,0.9761077122728958,0.9717741935483871,0.9725877698007404,0.8791170531300049,0.9956644687154611
2,LR,0.904930429522081,0.9245061265316329,0.9395161290322581,0.9295698481284789,0.7318918918918919,0.9694566765013001
3,KNN,0.9343617664851784,0.9700124927102034,0.967741935483871,0.9679015043169659,0.8537412458532989,0.9946164621253294
1,SVC,0.9429824561403508,0.9711419051946086,0.9637096774193549,0.9652704423698185,0.8444057162774485,0.9893704541157731
2,LR,0.9187840290381126,0.9370061265316328,0.9395161290322581,0.9358399550757008,0.7328162034044388,0.9756532382669324
3,KNN,0.9360556563823353,0.9629923105776443,0.9596774193548387,0.9600144907847665,0.8222859190254389,0.9933512420464309
1,SVC,0.9376890502117362,0.9549396448729041,0.9475806451612904,0.9470534928131183,0.7651515151515151,0.9638597608051601
2,LR,0.9135511191772535,0.9370061265316328,0.9395161290322581,0.9358399550757008,0.7328162034044388,0.9760133137237909
3,KNN,0.9412280701754387,0.9646057347670252,0.9596774193548387,0.9597324692813461,0.8195576251455181,0.9902107624305637

In [20]:
df = df.sort_values('Model')

In [21]:
df

,Model,Accuracy,Precision,Recall,F1 Score,Cohen Kappa,AUC
3,KNN,0.9309134906231094,0.9672381613068397,0.9637096774193549,0.9633179964270063,0.8352645951730755,0.9926904803983257
3,KNN,0.9343617664851784,0.9700124927102034,0.967741935483871,0.9679015043169659,0.8537412458532989,0.9946164621253294
3,KNN,0.9360556563823353,0.9629923105776443,0.9596774193548387,0.9600144907847665,0.8222859190254389,0.9933512420464309
3,KNN,0.9412280701754387,0.9646057347670252,0.9596774193548387,0.9597324692813461,0.8195576251455181,0.9902107624305637
2,LR,0.9066545674531156,0.9348355328204978,0.9354838709677419,0.9323924731182796,0.7189403598243377,0.9806116454904993
2,LR,0.904930429522081,0.9245061265316329,0.9395161290322581,0.9295698481284789,0.7318918918918919,0.9694566765013001
2,LR,0.9187840290381126,0.9370061265316328,0.9395161290322581,0.9358399550757008,0.7328162034044388,0.9756532382669324
2,LR,0.9135511191772535,0.9370061265316328,0.9395161290322581,0.9358399550757008,0.7328162034044388,0.9760133137237909
1,SVC,0.9481851179673322,0.9742525876796302,0.967741935483871,0.9678443365486884,0.859629262770624,0.9949207267839908
1,SVC,0.9447065940713854,0.9761077122728958,0.9717741935483871,0.9725877698007404,0.8791170531300049,0.9956644687154611
1,SVC,0.9429824561403508,0.9711419051946086,0.9637096774193549,0.9652704423698185,0.8444057162774485,0.9893704541157731
1,SVC,0.9376890502117362,0.9549396448729041,0.9475806451612904,0.9470534928131183,0.7651515151515151,0.9638597608051601

In [22]:
df.to_csv('Extremely Imbalance 70-30 Applying HyperParameter IG.csv', index=False)