In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv('LMCH Moderately Imbalance 80-20 Applying IG Top 4 features.csv')
df2 = pd.read_csv('LMCH Moderately Imbalance 80-20 Applying IG Top 5 features.csv')
df3 = pd.read_csv('LMCH Moderately Imbalance 80-20 Applying IG Top 7 features.csv')
df4 = pd.read_csv('LMCH Moderately Imbalance 80-20 Applying IG Top 9 features.csv')

In [3]:
df4

,Unnamed: 0,0,1,2,3,4,5
0,Metrics,Accuracy,Precision,Recall,F1 Score,Cohen Kappa,AUC
1,SVC,0.9245283018867925,0.9216695254431103,0.9245283018867925,0.9200359389038634,0.875,0.9818470418470419
2,LR,0.8867924528301887,0.8919382504288165,0.8867924528301887,0.8878032345013478,0.8161849710982659,0.9588119288119289
3,KNN,0.8301886792452831,0.8160204575298915,0.8301886792452831,0.8213921555736882,0.7179183914843288,0.9561940836940837

In [4]:
df2 = df2.drop(0, axis=0)
df3 = df3.drop(0, axis=0)
df4 = df4.drop(0, axis=0)
df2

,Unnamed: 0,0,1,2,3,4,5
1,SVC,0.9433962264150944,0.9414264980302716,0.9433962264150944,0.9416944136145023,0.906635349383441,0.9855218855218855
2,LR,0.8867924528301887,0.8867924528301887,0.8867924528301887,0.8729730886065117,0.8103756708407871,0.9622655122655122
3,KNN,0.8679245283018868,0.8747379454926624,0.8679245283018868,0.8708464517882625,0.7864133563615429,0.9720454545454545

In [5]:
df = pd.concat([df1, df2, df3, df4])
df

,Unnamed: 0,0,1,2,3,4,5
0,Metrics,Accuracy,Precision,Recall,F1 Score,Cohen Kappa,AUC
1,SVC,0.9811320754716981,0.9832285115303984,0.9811320754716981,0.9814451179601014,0.9693995381062356,0.993939393939394
2,LR,0.9056603773584906,0.9041837571780147,0.9056603773584906,0.8980659533533601,0.8426365795724465,0.9702861952861953
3,KNN,0.8867924528301887,0.915666094911378,0.8867924528301887,0.8948604720583846,0.8216489063376332,0.9822186147186147
1,SVC,0.9433962264150944,0.9414264980302716,0.9433962264150944,0.9416944136145023,0.906635349383441,0.9855218855218855
2,LR,0.8867924528301887,0.8867924528301887,0.8867924528301887,0.8729730886065117,0.8103756708407871,0.9622655122655122
3,KNN,0.8679245283018868,0.8747379454926624,0.8679245283018868,0.8708464517882625,0.7864133563615429,0.9720454545454545
1,SVC,0.9622641509433962,0.9622641509433962,0.9622641509433962,0.9622641509433962,0.9383720930232559,0.9817340067340069
2,LR,0.9056603773584906,0.9020664869721473,0.9056603773584906,0.9032060131922074,0.844847775175644,0.955026455026455
3,KNN,0.9056603773584906,0.9112074690417595,0.9056603773584906,0.9070928417386283,0.8478760045924225,0.9739117364117363
1,SVC,0.9245283018867925,0.9216695254431103,0.9245283018867925,0.9200359389038634,0.875,0.9818470418470419
2,LR,0.8867924528301887,0.8919382504288165,0.8867924528301887,0.8878032345013478,0.8161849710982659,0.9588119288119289
3,KNN,0.8301886792452831,0.8160204575298915,0.8301886792452831,0.8213921555736882,0.7179183914843288,0.9561940836940837

In [6]:
df = df.drop(0, axis=0)

In [7]:
df.rename(columns={'Unnamed: 0': 'Model', '0': 'Accuracy', '1': 'Precision', '2': 'Recall', '3': 'F1 Score', '4': 'Cohen Kappa', '5': 'AUC'}, inplace=True)

In [8]:
df

,Model,Accuracy,Precision,Recall,F1 Score,Cohen Kappa,AUC
1,SVC,0.9811320754716981,0.9832285115303984,0.9811320754716981,0.9814451179601014,0.9693995381062356,0.993939393939394
2,LR,0.9056603773584906,0.9041837571780147,0.9056603773584906,0.8980659533533601,0.8426365795724465,0.9702861952861953
3,KNN,0.8867924528301887,0.915666094911378,0.8867924528301887,0.8948604720583846,0.8216489063376332,0.9822186147186147
1,SVC,0.9433962264150944,0.9414264980302716,0.9433962264150944,0.9416944136145023,0.906635349383441,0.9855218855218855
2,LR,0.8867924528301887,0.8867924528301887,0.8867924528301887,0.8729730886065117,0.8103756708407871,0.9622655122655122
3,KNN,0.8679245283018868,0.8747379454926624,0.8679245283018868,0.8708464517882625,0.7864133563615429,0.9720454545454545
1,SVC,0.9622641509433962,0.9622641509433962,0.9622641509433962,0.9622641509433962,0.9383720930232559,0.9817340067340069
2,LR,0.9056603773584906,0.9020664869721473,0.9056603773584906,0.9032060131922074,0.844847775175644,0.955026455026455
3,KNN,0.9056603773584906,0.9112074690417595,0.9056603773584906,0.9070928417386283,0.8478760045924225,0.9739117364117363
1,SVC,0.9245283018867925,0.9216695254431103,0.9245283018867925,0.9200359389038634,0.875,0.9818470418470419
2,LR,0.8867924528301887,0.8919382504288165,0.8867924528301887,0.8878032345013478,0.8161849710982659,0.9588119288119289
3,KNN,0.8301886792452831,0.8160204575298915,0.8301886792452831,0.8213921555736882,0.7179183914843288,0.9561940836940837

In [9]:
df = df.sort_values('Model')

In [10]:
df

,Model,Accuracy,Precision,Recall,F1 Score,Cohen Kappa,AUC
3,KNN,0.8867924528301887,0.915666094911378,0.8867924528301887,0.8948604720583846,0.8216489063376332,0.9822186147186147
3,KNN,0.8679245283018868,0.8747379454926624,0.8679245283018868,0.8708464517882625,0.7864133563615429,0.9720454545454545
3,KNN,0.9056603773584906,0.9112074690417595,0.9056603773584906,0.9070928417386283,0.8478760045924225,0.9739117364117363
3,KNN,0.8301886792452831,0.8160204575298915,0.8301886792452831,0.8213921555736882,0.7179183914843288,0.9561940836940837
2,LR,0.9056603773584906,0.9041837571780147,0.9056603773584906,0.8980659533533601,0.8426365795724465,0.9702861952861953
2,LR,0.8867924528301887,0.8867924528301887,0.8867924528301887,0.8729730886065117,0.8103756708407871,0.9622655122655122
2,LR,0.9056603773584906,0.9020664869721473,0.9056603773584906,0.9032060131922074,0.844847775175644,0.955026455026455
2,LR,0.8867924528301887,0.8919382504288165,0.8867924528301887,0.8878032345013478,0.8161849710982659,0.9588119288119289
1,SVC,0.9811320754716981,0.9832285115303984,0.9811320754716981,0.9814451179601014,0.9693995381062356,0.993939393939394
1,SVC,0.9433962264150944,0.9414264980302716,0.9433962264150944,0.9416944136145023,0.906635349383441,0.9855218855218855
1,SVC,0.9622641509433962,0.9622641509433962,0.9622641509433962,0.9622641509433962,0.9383720930232559,0.9817340067340069
1,SVC,0.9245283018867925,0.9216695254431103,0.9245283018867925,0.9200359389038634,0.875,0.9818470418470419

In [11]:
df.to_csv('Moderately Imbalance 80-20 Applying IG.csv', index=False)